package com.fouri.commonexcelmodule.model.vo;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Jan 09 15:11:39 IST 2019
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class ActionsROVOImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public ActionsROVOImpl() {
    }
}

