package com.fouri.commonexcelmodule.model.am.common;

import java.util.ArrayList;
import java.util.Map;

import oracle.jbo.ApplicationModule;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Jan 14 11:36:18 IST 2019
// ---------------------------------------------------------------------
public interface AppModule extends ApplicationModule {
    String uploadData(String ifaceId, String parentIfaceId, Map processedData);


    void invokeProcedure(String procedureName, String batchId);

    String parentInterfaceId(String parentInterfaceName);

    Map<String, ArrayList<String>> refreshAndExecuteVO(String ifaceId, String StagingTable, String batchId,
                                                       String interfaceStatus);
}

